### ISSUE TITLE
Edit email address used for reset password

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/oxleas-adhd#32] opened 2017-07-05 12:03 UTC
+ [x] As a user who has forgotten my password, IF I have an account and enter my email address, I will get an email from oxl-tr.focusadhd@nhs.net, with a link to reset my password.

**Comment by katyedwards** [comment] 2017-07-05 12:07
Oxleas email: oxl-tr.focusadhd@nhs.net

**Comment by markwilliamfirth** [comment] 2017-08-14 11:20
Blocked by #50

**Comment by markwilliamfirth** [comment] 2017-08-24 06:56
@katbow is this a quick one @Cleop can do?

**Comment by katbow** [comment] 2017-08-24 11:31
it's easier for Rob or I to do as we already have server access. @katyedwards I sent the email out to oxl-tr.focusadhd@nhs.net to be verified so that this can be set on the server.

**Comment by MollieCourtenay** [comment] 2017-08-24 11:45
@katbow Oxleas said at 12.30 they have verified email from AWS

**Comment by katyedwards** [comment] 2017-08-25 10:15
@RobStallion assigning to you while you wait for subdomain for SSL

**Comment by RobStallion** [comment] 2017-08-25 12:35
![image](https://user-images.githubusercontent.com/15571853/29714258-45c2694a-899a-11e7-83ae-95e5863d70d8.png)

when running the site manually

**Comment by RobStallion** [comment] 2017-08-25 12:44
![image](https://user-images.githubusercontent.com/15571853/29714496-677b0b90-899b-11e7-88b4-a1ef61a93571.png)

@katyedwards Seems to be working now. The emails I received when into my spam so when you test it just be careful of that.

**Comment by katyedwards** [comment] 2017-08-25 13:31
- [ ] Subject line  needs to say: Headscape Focus Reset Password Instructions

- [ ] The reset link needs to go to headscape focus not staging - you may not be able to do this before the subdomain is confirmed?

![screenshot 2017-08-25 14 28 16](https://user-images.githubusercontent.com/24604903/29716067-d8a0faa4-89a1-11e7-9c0e-43566c739312.png)

@RobStallion

**Comment by katbow** [comment] 2017-08-25 13:36
@RobStallion @katyedwards the email can be set up to link to the correct subdomain address, but you're correct that it won't actually be functioning until that's set up.

**Comment by katyedwards** [comment] 2017-08-25 13:41
@katbow can we test it if it goes to staging?  If not then it might as well be set up and wait.

**Comment by RobStallion** [comment] 2017-08-25 13:49
@katyedwards As @katbow I can't use the subdomain until it's set up as it wont work but it is currently redirecting to the correct url with the IP address. Going to push those changes up

**Comment by katbow** [comment] 2017-08-25 13:57
Do you mean if it goes to the staging.healthlocker.uk site? No, it wouldn't work for testing because it's separate databases, so the user being tested & relative reset tokens would not be present there.

**Comment by katyedwards** [comment] 2017-08-30 15:16
Done, thanks!

**Closed by katyedwards** 2017-08-30 15:16 UTC
Labels: awaiting-review, priority-3, technical
